spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-clientes
          uri: http://localhost:8082/
          predicates:
            - Path=/clientes/**

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with0eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka